version: '2.3'

services:
    graphonomy_server_gpu:
        container_name: graphonomy_server_gpu_container
        image: graphonomy_wrapper_image
        runtime: nvidia
        build:
            context: "."
            dockerfile: Dockerfile
        volumes:
            - ${PWD}:/home/ubuntu/share/graphonomy_wrapper
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        ports:
            - "5001:5001"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "python3 app.py --host 0.0.0.0 --port 5001 --device gpu"

    graphonomy_server_cpu:
        container_name: graphonomy_server_cpu_container
        image: graphonomy_wrapper_image
        build:
            context: "."
            dockerfile: Dockerfile
        volumes:
            - ${PWD}:/home/ubuntu/share/graphonomy_wrapper
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        ports:
            - "5002:5002"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "python3 app.py --host 0.0.0.0 --port 5002 --device cpu"
